name: Cache Action
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 */4 * * *

jobs:
  stats:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Stats Card
    steps:
      - uses: actions/checkout@v3
        name: Check out current commit

      - uses: suisei-cn/actions-download-file@v1.3.0
        id: stats
        name: Download the stats file
        with:
          url: "https://github-readme-stats-siph.vercel.app/api?username=siph&hide_rank=true&hide_title=true&theme=gruvbox&show_icons=true&count_private=true&line_height=21"
          target: grs
          filename: stats.svg

      - uses: suisei-cn/actions-download-file@v1.3.0
        id: languages
        name: Download the languages file
        with:
          url: "https://github-readme-stats-siph.vercel.app/api/top-langs/?username=siph&hide_title=true&theme=gruvbox&layout=compact&exclude_repo=neovim-flake&hide=css,html,scss"
          target: grs
          filename: languages.svg

      - uses: actions/upload-artifact@master
        with:
          name: stats
          path: grs

  push:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push
    needs: [stats]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: stats
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: resource/grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
